package a.a.a;

import static com.besome.sketch.Config.VAR_DEFAULT_MIN_SDK_VERSION;
import static com.besome.sketch.Config.VAR_DEFAULT_TARGET_SDK_VERSION;
import static mod.hey.studios.util.ProjectFile.getDefaultColor;

import android.content.Context;
import android.util.Log;

import com.besome.sketch.beans.BlockBean;
import com.besome.sketch.beans.ComponentBean;
import com.besome.sketch.beans.ProjectFileBean;
import com.besome.sketch.beans.ProjectLibraryBean;
import com.besome.sketch.beans.SrcCodeBean;
import com.besome.sketch.beans.ViewBean;
import com.besome.sketch.editor.manage.library.material3.Material3LibraryManager;

import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Pattern;

import mod.hey.studios.build.BuildSettings;
import mod.hey.studios.project.ProjectSettings;
import mod.hey.studios.util.ProjectFile;
import mod.hilal.saif.blocks.CommandBlock;
import mod.pranav.viewbinding.ViewBindingBuilder;
import pro.sketchware.SketchApplication;
import pro.sketchware.util.library.BuiltInLibraryManager;
import pro.sketchware.utility.FileUtil;
import pro.sketchware.xml.XmlBuilder;
import pro.sketchware.xml.XmlBuilderHelper;

public class yq {

    private static final String FIREBASE_DATABASE_STORAGE_LOCATION_MATCHER = "(-default-rtdb)?\\.[a-z](.?)+";
    private static final Pattern PACKAGE_PLACEHOLDER_PATTERN = Pattern.compile("<\\?package_name\\?>");

    public final String assetsPath;
    public final String fontsPath;
    public final String resourcesApkPath;
    public final String classesDexPath;
    public final String unsignedUnalignedApkPath;
    public final String finalToInstallApkPath;
    public final String releaseApkPath;
    public final String unsignedAlignedApkPath;
    public final String sc_id;
    public final String projectMyscPath;
    public final String projectName;
    public final String packageName;
    public final String applicationName;
    public final int colorAccent;
    public final int colorPrimary;
    public final int colorPrimaryDark;
    public final int colorControlHighlight;
    public final int colorControlNormal;
    public final String versionCode;
    public final String versionName;
    public final String packageNameAsFolders;
    public final String proguardAaptRules;
    public final String proguardAutoGeneratedExclusions;
    public final String proguardClassesPath;
    public final String proguardMappingPath;
    public final String proguardSeedsPath;
    public final String proguardUsagePath;
    public final ProjectSettings projectSettings;
    public final String androidManifestPath;
    public final String generatedFilesPath;
    public final String binDirectoryPath;
    public final String compiledClassesPath;
    public final String rJavaDirectoryPath;
    public final String resDirectoryPath;
    public final String proguardFilePath;
    public final String layoutFilesPath;
    public final String javaFilesPath;
    public final String importedSoundsPath;
    public final HashMap<String, Object> metadata;
    private final Material3LibraryManager material3LibraryManager;
    private final oB fileUtil;
    private final Context context;
    public jq N;
    public boolean generateDataBindingClasses;
    public boolean isAndroidStudioExport;
    private ExportType exportingType;

    public yq(Context context, String sc_id) {
        this(context, wq.d(sc_id), lC.b(sc_id));
    }

    public yq(Context context, String myscFolderPath, HashMap<String, Object> metadata) {
        this.context = context;
        this.metadata = metadata;
        N = new jq();
        sc_id = yB.c(metadata, "sc_id");
        material3LibraryManager = new Material3LibraryManager(sc_id);
        N.sc_id = sc_id;
        projectMyscPath = myscFolderPath.endsWith(File.separator) ? myscFolderPath : myscFolderPath + File.separator;
        packageName = yB.c(metadata, "my_sc_pkg_name");
        projectName = yB.c(metadata, "my_ws_name");
        applicationName = yB.c(metadata, "my_app_name");
        versionCode = yB.c(metadata, "sc_ver_code");
        versionName = yB.c(metadata, "sc_ver_name");

        colorAccent = yB.a(metadata, ProjectFile.COLOR_ACCENT, getDefaultColor(ProjectFile.COLOR_ACCENT));
        colorPrimary = yB.a(metadata, ProjectFile.COLOR_PRIMARY, getDefaultColor(ProjectFile.COLOR_PRIMARY));
        colorPrimaryDark = yB.a(metadata, ProjectFile.COLOR_PRIMARY_DARK, getDefaultColor(ProjectFile.COLOR_PRIMARY_DARK));
        colorControlHighlight = yB.a(metadata, ProjectFile.COLOR_CONTROL_HIGHLIGHT, getDefaultColor(ProjectFile.COLOR_CONTROL_HIGHLIGHT));
        colorControlNormal = yB.a(metadata, ProjectFile.COLOR_CONTROL_NORMAL, getDefaultColor(ProjectFile.COLOR_CONTROL_NORMAL));

        projectSettings = new ProjectSettings(sc_id);
        fileUtil = new oB(true);
        packageNameAsFolders = packageName.replaceAll("\\.", File.separator);
        binDirectoryPath = projectMyscPath + "bin";
        compiledClassesPath = binDirectoryPath + File.separator + "classes";
        proguardClassesPath = binDirectoryPath + File.separator + "classes_proguard.jar";
        proguardAaptRules = binDirectoryPath + File.separator + "aapt_rules.pro";
        proguardSeedsPath = binDirectoryPath + File.separator + "seeds.txt";
        proguardUsagePath = binDirectoryPath + File.separator + "usage.txt";
        proguardMappingPath = binDirectoryPath + File.separator + "mapping.txt";
        proguardAutoGeneratedExclusions = binDirectoryPath + File.separator + "rules_generated.pro";
        rJavaDirectoryPath = projectMyscPath + "gen";
        generatedFilesPath = projectMyscPath + "app" + File.separator + "src" + File.separator + "main";
        javaFilesPath = generatedFilesPath + File.separator + "java";
        resDirectoryPath = generatedFilesPath + File.separator + "res";
        proguardFilePath = projectMyscPath + "app" + File.separator + "proguard-rules.pro";
        layoutFilesPath = resDirectoryPath + File.separator + "layout";
        importedSoundsPath = resDirectoryPath + File.separator + "raw";
        assetsPath = generatedFilesPath + File.separator + "assets";
        fontsPath = assetsPath + File.separator + "fonts";
        androidManifestPath = projectMyscPath + "app" + File.separator + "src" + File.separator + "main" + File.separator + "AndroidManifest.xml";
        resourcesApkPath = binDirectoryPath + File.separator + projectName + ".apk.res";
        classesDexPath = binDirectoryPath + File.separator + "classes.dex";
        unsignedUnalignedApkPath = binDirectoryPath + File.separator + projectName + ".apk.unsigned";
        unsignedAlignedApkPath = unsignedUnalignedApkPath + ".aligned";
        finalToInstallApkPath = binDirectoryPath + File.separator + projectName + ".apk";
        releaseApkPath = wq.o() + File.separator + projectName + "_release.apk";
    }

    public void a() {
        File file = new File(resDirectoryPath + File.separator + "values-v21");
        if (file.exists()) {
            fileUtil.a(file);
        }
    }

    public void c(Context context) {
        fileUtil.f(binDirectoryPath);
        fileUtil.f(compiledClassesPath);
        fileUtil.f(rJavaDirectoryPath);
        fileUtil.f(javaFilesPath);
        fileUtil.f(resDirectoryPath);
        fileUtil.f(layoutFilesPath);
        fileUtil.f(importedSoundsPath);
        fileUtil.f(assetsPath);
        fileUtil.f(fontsPath);
    }

    public void e() {
        fileUtil.f(binDirectoryPath);
        fileUtil.f(compiledClassesPath);
        fileUtil.f(rJavaDirectoryPath);
    }

    public void f() {
        fileUtil.b(binDirectoryPath);
        fileUtil.b(rJavaDirectoryPath);
    }

    public void generateGradleFiles() {
        fileUtil.b(projectMyscPath + File.separator + "app" + File.separator + "build.gradle",
                Lx.getBuildGradleString(VAR_DEFAULT_TARGET_SDK_VERSION, VAR_DEFAULT_MIN_SDK_VERSION, projectSettings.getValue(ProjectSettings.SETTING_TARGET_SDK_VERSION, String.valueOf(VAR_DEFAULT_TARGET_SDK_VERSION)), N, projectSettings.getValue(ProjectSettings.SETTING_ENABLE_VIEWBINDING, ProjectSettings.SETTING_GENERIC_VALUE_FALSE).equals(ProjectSettings.SETTING_GENERIC_VALUE_TRUE)));
        fileUtil.b(projectMyscPath + File.separator + "settings.gradle", Lx.a());
        fileUtil.b(projectMyscPath + File.separator + "build.gradle", Lx.c("8.12.0", "4.4.3"));

        fileUtil.b(projectMyscPath + File.separator + "gradle.properties", """
                android.enableR8.fullMode=false
                android.enableJetifier=true
                android.useAndroidX=true
                """.trim());
    }

    public void a(Context context, String str) {
        try {
            KB.a(context, str, resDirectoryPath);
        } catch (Exception e2) {
            Log.e("ERROR", e2.getMessage(), e2);
        }
    }

    public void a(String iconPath) {
        try {
            fileUtil.a(iconPath, resDirectoryPath + File.separator + "mipmap-xhdpi" + File.separator + "ic_launcher.png");
        } catch (Exception e2) {
            e2.printStackTrace();
        }
    }

    public void aa(String iconPath) {
        try {
            FileUtil.copyDirectory(new File(iconPath), new File(resDirectoryPath + File.separator));
        } catch (Exception e2) {
            e2.printStackTrace();
        }
    }

    public void createLauncherIconXml(String content) {
        try {
            fileUtil.b(resDirectoryPath + File.separator + "mipmap-anydpi-v26" + File.separator + "ic_launcher.xml", content);
        } catch (Exception e2) {
            e2.printStackTrace();
        }
    }

    public void generateDebugFiles(Context context) {
        boolean logcatEnabled = N.isDebugBuild && new BuildSettings(sc_id).getValue(
                        BuildSettings.SETTING_ENABLE_LOGCAT, BuildSettings.SETTING_GENERIC_VALUE_TRUE)
                .equals(BuildSettings.SETTING_GENERIC_VALUE_TRUE);

        String javaDir = FileUtil.getExternalStorageDir() + "/.sketchware/data/" + sc_id + "/files/java/";

        File debugActivityFile = new File(javaDir, "DebugActivity.java");
        if (!debugActivityFile.exists()) {
            String debugActivityContent = fileUtil.b(
                    context,
                    "debug" + File.separator + "DebugActivity.java"
            );
            debugActivityContent = PACKAGE_PLACEHOLDER_PATTERN.matcher(debugActivityContent).replaceAll(packageName);
            fileUtil.b(javaFilesPath + File.separator + packageNameAsFolders + File.separator + "DebugActivity.java", debugActivityContent);
        }

        String customApplicationClassName = new ProjectSettings(sc_id).getValue(
                ProjectSettings.SETTING_APPLICATION_CLASS, ".SketchApplication");
        boolean notUsingCustomApplicationClass = customApplicationClassName.equals(".SketchApplication");

        if (!customApplicationClassName.startsWith(".")) {
            customApplicationClassName = "." + customApplicationClassName;
        }

        String fullCustomClassName = packageName + customApplicationClassName;

        int lastDot = fullCustomClassName.lastIndexOf('.');
        String customClassSimpleName = fullCustomClassName.substring(lastDot + 1);
        String customClassPackage = fullCustomClassName.substring(0, lastDot);
        String customClassPackageAsFolders = customClassPackage.replace('.', File.separatorChar);

        File targetApplicationFile = new File(javaDir + File.separator +
                customApplicationClassName.substring(1).replace('.', '/') + ".java");

        if (!targetApplicationFile.exists()) {
            boolean applyMultiDex = projectSettings.getMinSdkVersion() < 21;
            String sketchApplicationFileContent = fileUtil.b(
                    context,
                    "debug" + File.separator + "SketchApplication.java"
            );
            sketchApplicationFileContent = PACKAGE_PLACEHOLDER_PATTERN.matcher(sketchApplicationFileContent).replaceAll(packageName);

            if (applyMultiDex) {
                sketchApplicationFileContent = sketchApplicationFileContent.replaceAll(
                        "Application \\{", "androidx.multidex.MultiDexApplication {");
            }
            if (logcatEnabled) {
                sketchApplicationFileContent = sketchApplicationFileContent.replace(
                                "super.onCreate();", "SketchLogger.startLogging();\n        super.onCreate();")
                        .replace("Process.killProcess(Process.myPid());",
                                "SketchLogger.broadcastLog(Log.getStackTraceString(throwable));\n" +
                                        "                    Process.killProcess(Process.myPid());"
                        );
            }
            if (new Material3LibraryManager(sc_id).isDynamicColorsEnabled()) {
                sketchApplicationFileContent = sketchApplicationFileContent.replace(
                                "mApplicationContext = getApplicationContext();",
                                "mApplicationContext = getApplicationContext();\n        DynamicColors.applyToActivitiesIfAvailable(this);")
                        .replace("import android.util.Log;", "import android.util.Log;\nimport com.google.android.material.color.DynamicColors;");
            }
            if (!notUsingCustomApplicationClass) {
                sketchApplicationFileContent = sketchApplicationFileContent.replaceAll(
                        "public class SketchApplication", "public class " + customClassSimpleName);
                sketchApplicationFileContent = sketchApplicationFileContent.replaceAll(
                        "package " + packageName + ";", "package " + customClassPackage + ";");

                String imports = "import android.util.Log;\nimport " + packageName + ".DebugActivity;";
                if (logcatEnabled) {
                    imports += "\nimport " + packageName + ".SketchLogger;";
                }
                sketchApplicationFileContent = sketchApplicationFileContent.replace(
                        "import android.util.Log;", imports);
            }

            fileUtil.b(javaFilesPath + File.separator
                    + customClassPackageAsFolders + File.separator
                    + customClassSimpleName + ".java", sketchApplicationFileContent);
        }

        if (logcatEnabled) {
            File sketchLoggerFile = new File(javaDir, "SketchLogger.java");
            if (!sketchLoggerFile.exists()) {
                String sketchLoggerFileContent = fileUtil.b(
                        context,
                        "debug" + File.separator + "SketchLogger.java"
                );

                sketchLoggerFileContent = PACKAGE_PLACEHOLDER_PATTERN.matcher(sketchLoggerFileContent).replaceAll(packageName);
                sketchLoggerFileContent = sketchLoggerFileContent.replace("<?class_name_package?>", customClassPackage);
                sketchLoggerFileContent = sketchLoggerFileContent.replace("<?class_name?>", customClassSimpleName);

                fileUtil.b(javaFilesPath + File.separator + packageNameAsFolders + File.separator + "SketchLogger.java",
                        sketchLoggerFileContent);
            }
        }
    }

    public void a(String fileName, String fileContent) {
        if (fileName.endsWith("java")) {
            fileUtil.b(javaFilesPath + File.separator + packageNameAsFolders + File.separator + fileName, fileContent);
        } else if (fileName.equals("AndroidManifest.xml")) {
            fileUtil.b(androidManifestPath, fileContent);
        } else if (fileName.equals("colors.xml") || fileName.equals("styles.xml") || fileName.equals("strings.xml")) {
            fileUtil.b(resDirectoryPath + File.separator + "values" + File.separator + fileName, fileContent);
        } else if (fileName.equals("provider_paths.xml")) {
            fileUtil.b(resDirectoryPath + File.separator + "xml" + File.separator + fileName, fileContent);
        } else {
            fileUtil.b(layoutFilesPath + File.separator + fileName, fileContent);
        }
    }

    public void a(iC projectLibraryManager, hC projectFileManager, eC projectDataManager) {
        a(projectLibraryManager, projectFileManager, projectDataManager, ExportType.DEBUG_APP);
    }

    public void a(iC projectLibraryManager, hC projectFileManager, eC projectDataManager, ExportType exportingType) {
        ProjectLibraryBean adMob = projectLibraryManager.b();
        ProjectLibraryBean appCompat = projectLibraryManager.c();
        ProjectLibraryBean firebase = projectLibraryManager.d();
        ProjectLibraryBean googleMaps = projectLibraryManager.e();
        this.exportingType = exportingType;
        N = new jq();
        N.packageName = packageName;
        N.projectName = applicationName;
        N.versionCode = versionCode;
        N.versionName = versionName;
        N.sc_id = sc_id;
        N.isDebugBuild = exportingType == ExportType.DEBUG_APP;
        isAndroidStudioExport = exportingType == ExportType.ANDROID_STUDIO;
        generateDataBindingClasses = !(exportingType == ExportType.DEBUG_APP || exportingType == ExportType.ANDROID_STUDIO);
        if (firebase.useYn.equals(ProjectLibraryBean.LIB_USE_Y)) {
            N.isFirebaseEnabled = true;
            N.addPermission(jq.PERMISSION_INTERNET);
            N.addPermission(jq.PERMISSION_ACCESS_NETWORK_STATE);
        }
        if (appCompat.useYn.equals(ProjectLibraryBean.LIB_USE_Y)) {
            N.g = true;
        }
        if (adMob.useYn.equals(ProjectLibraryBean.LIB_USE_Y)) {
            N.isAdMobEnabled = true;
            N.addPermission(jq.PERMISSION_INTERNET);
            N.addPermission(jq.PERMISSION_ACCESS_NETWORK_STATE);
            N.setupAdmob(adMob);
        }
        if (googleMaps.useYn.equals(ProjectLibraryBean.LIB_USE_Y)) {
            N.isMapUsed = true;
            N.addPermission(jq.PERMISSION_INTERNET);
            N.addPermission(jq.PERMISSION_ACCESS_NETWORK_STATE);
            N.setupGoogleMap(googleMaps);
        }
        for (ProjectFileBean customView : projectFileManager.c()) {
            for (ViewBean viewBean : eC.a(projectDataManager.d(customView.getXmlName()))) {
                var classNameParts = viewBean.convert.split("\\.");
                var className = classNameParts[classNameParts.length - 1];
                switch (className) {
                    case "CircleImageView" -> N.x.isCircleImageViewUsed = true;
                    case "CodeView" -> N.x.isCodeViewUsed = true;
                    case "LottieAnimationView" -> N.x.isLottieUsed = true;
                    case "OTPView" -> N.x.isOTPViewUsed = true;
                    case "PatternLockView" -> N.x.isPatternLockViewUsed = true;
                    case "WaveSideBar" -> N.x.isWaveSideBarUsed = true;
                    case "YouTubePlayerView" -> N.x.isYoutubePlayerUsed = true;
                    case "SwipeRefreshLayout" -> N.x.isSwipeRefreshLayoutUsed = true;
                }
            }
        }
        for (ProjectFileBean activity : projectFileManager.b()) {
            if (activity.hasActivityOption(ProjectFileBean.OPTION_ACTIVITY_DRAWER)) {
                N.a(activity.getActivityName()).hasDrawer = true;
            }
            for (ComponentBean component : projectDataManager.e(activity.getJavaName())) {
                switch (component.type) {
                    case ComponentBean.COMPONENT_TYPE_CAMERA, 35 -> {
                        N.g = true;
                        N.u = true;
                        N.addPermission(activity.getActivityName(), jq.PERMISSION_CAMERA);
                        N.addPermission(activity.getActivityName(), jq.PERMISSION_READ_EXTERNAL_STORAGE);
                        N.addPermission(activity.getActivityName(), jq.PERMISSION_WRITE_EXTERNAL_STORAGE);
                    }
                    case ComponentBean.COMPONENT_TYPE_FILE_PICKER ->
                            N.addPermission(activity.getActivityName(), jq.PERMISSION_READ_EXTERNAL_STORAGE);
                    case ComponentBean.COMPONENT_TYPE_FIREBASE -> {
                        N.isGsonUsed = true;
                        N.isFirebaseDatabaseUsed = true;
                        N.addPermission(activity.getActivityName(), jq.PERMISSION_INTERNET);
                        N.addPermission(activity.getActivityName(), jq.PERMISSION_ACCESS_NETWORK_STATE);
                    }
                    case ComponentBean.COMPONENT_TYPE_FIREBASE_STORAGE -> {
                        N.isFirebaseStorageUsed = true;
                        N.addPermission(activity.getActivityName(), jq.PERMISSION_READ_EXTERNAL_STORAGE);
                        N.addPermission(activity.getActivityName(), jq.PERMISSION_WRITE_EXTERNAL_STORAGE);
                    }
                    case ComponentBean.COMPONENT_TYPE_VIBRATOR ->
                            N.addPermission(activity.getActivityName(), jq.PERMISSION_VIBRATE);
                    case ComponentBean.COMPONENT_TYPE_FIREBASE_AUTH -> {
                        N.isFirebaseAuthUsed = true;
                        N.a(activity.getActivityName()).usesFirebaseAuth = true;
                    }
                    case ComponentBean.COMPONENT_TYPE_REQUEST_NETWORK -> {
                        N.isGsonUsed = true;
                        N.isHttp3Used = true;
                        N.addPermission(activity.getActivityName(), jq.PERMISSION_INTERNET);
                        N.addPermission(activity.getActivityName(), jq.PERMISSION_ACCESS_NETWORK_STATE);
                    }
                    case ComponentBean.COMPONENT_TYPE_TEXT_TO_SPEECH -> N.isTextToSpeechUsed = true;
                    case ComponentBean.COMPONENT_TYPE_SPEECH_TO_TEXT -> {
                        N.isSpeechToTextUsed = true;
                        N.addPermission(activity.getActivityName(), jq.PERMISSION_RECORD_AUDIO);
                    }
                    case ComponentBean.COMPONENT_TYPE_BLUETOOTH_CONNECT -> {
                        N.addPermission(activity.getActivityName(), jq.PERMISSION_BLUETOOTH);
                        N.addPermission(activity.getActivityName(), jq.PERMISSION_BLUETOOTH_ADMIN);
                    }
                    case ComponentBean.COMPONENT_TYPE_LOCATION_MANAGER ->
                            N.addPermission(activity.getActivityName(), jq.PERMISSION_ACCESS_FINE_LOCATION);
                    case ComponentBean.COMPONENT_TYPE_FIREBASE_CLOUD_MESSAGE ->
                            N.x.isFCMUsed = true;
                    case ComponentBean.COMPONENT_TYPE_FIREBASE_AUTH_GOOGLE_LOGIN ->
                            N.x.isFBGoogleUsed = true;
                    default -> {
                    }
                }
            }

            for (ViewBean view : eC.a(projectDataManager.d(activity.getXmlName()))) {
                var classNameParts = view.convert.split("\\.");
                var className = classNameParts[classNameParts.length - 1];
                switch (className) {
                    case "CircleImageView" -> N.x.isCircleImageViewUsed = true;
                    case "CodeView" -> N.x.isCodeViewUsed = true;
                    case "LottieAnimationView" -> N.x.isLottieUsed = true;
                    case "OTPView" -> N.x.isOTPViewUsed = true;
                    case "PatternLockView" -> N.x.isPatternLockViewUsed = true;
                    case "WaveSideBar" -> N.x.isWaveSideBarUsed = true;
                    case "YouTubePlayerView" -> N.x.isYoutubePlayerUsed = true;
                    case "SwipeRefreshLayout" -> N.x.isSwipeRefreshLayoutUsed = true;
                }
            }

            for (Map.Entry<String, ArrayList<BlockBean>> entry : projectDataManager.b(activity.getJavaName()).entrySet()) {
                for (BlockBean block : entry.getValue()) {
                    switch (block.opCode) {
                        case "intentSetAction":
                            if (block.parameters.get(1).equals(uq.c[1])) {
                                N.addPermission(activity.getActivityName(), jq.PERMISSION_CALL_PHONE);
                            }
                            break;
                        case "fileutilread":
                        case "fileutilisexist":
                        case "fileutillistdir":
                        case "fileutilisdir":
                        case "fileutilisfile":
                        case "fileutillength":
                        case "fileutilStartsWith":
                        case "fileutilEndsWith":
                        case "getJpegRotate":
                        case "setImageFilePath":
                        case "fileutilGetLastSegmentPath":
                            N.addPermission(activity.getActivityName(), jq.PERMISSION_READ_EXTERNAL_STORAGE);
                            break;
                        case "fileutilwrite":
                        case "fileutilcopy":
                        case "fileutilcopydir":
                        case "fileutilmove":
                        case "fileutildelete":
                        case "fileutilmakedir":
                        case "resizeBitmapFileRetainRatio":
                        case "resizeBitmapFileToSquare":
                        case "resizeBitmapFileToCircle":
                        case "resizeBitmapFileWithRoundedBorder":
                        case "cropBitmapFileFromCenter":
                        case "rotateBitmapFile":
                        case "scaleBitmapFile":
                        case "skewBitmapFile":
                        case "setBitmapFileColorFilter":
                        case "setBitmapFileBrightness":
                        case "setBitmapFileContrast":
                            N.addPermission(activity.getActivityName(), jq.PERMISSION_READ_EXTERNAL_STORAGE);
                            N.addPermission(activity.getActivityName(), jq.PERMISSION_WRITE_EXTERNAL_STORAGE);
                            break;
                        case "strToMap":
                        case "mapToStr":
                        case "strToListMap":
                        case "listMapToStr":
                        case "GsonListTojsonString":
                        case "GsonStringToListString":
                        case "GsonStringToListNumber":
                            N.isGsonUsed = true;
                            break;
                        case "setImageUrl":
                            N.isGlideUsed = true;
                            N.addPermission(jq.PERMISSION_INTERNET);
                            break;
                        case "webViewLoadUrl":
                            N.addPermission(jq.PERMISSION_INTERNET);
                            N.addPermission(jq.PERMISSION_ACCESS_NETWORK_STATE);
                            break;
                        default:
                    }
                }
            }
            N.b();
        }
    }

    public void b(hC projectFileManager, eC projectDataManger, iC projectLibraryManager, BuiltInLibraryManager builtInLibraryManager) {
        ArrayList<SrcCodeBean> srcCodeBeans = a(projectFileManager, projectDataManger, builtInLibraryManager);
        if (N.u) {
            XmlBuilder pathsTag = new XmlBuilder("paths");
            pathsTag.addAttribute("xmlns", "android", "http://schemas.android.com/apk/res/android");
            XmlBuilder externalPathTag = new XmlBuilder("external-path");
            externalPathTag.addAttribute("", "name", "external_files");
            externalPathTag.addAttribute("", "path", ".");
            pathsTag.addChildNode(externalPathTag);
            srcCodeBeans.add(new SrcCodeBean("provider_paths.xml",
                    CommandBlock.applyCommands("xml/provider_paths.xml", pathsTag.toCode())));
        }

        for (SrcCodeBean bean : srcCodeBeans) {
            a(bean.srcFileName, bean.source);
        }
        if (N.isFirebaseEnabled || N.isAdMobEnabled || N.isMapUsed) {
            ProjectLibraryBean firebaseLibrary = projectLibraryManager.d();
            XmlBuilderHelper mx = new XmlBuilderHelper();
            mx.addInteger("google_play_services_version", 12451000);
            if (N.isFirebaseEnabled) {
                String databaseUrl;
                String projectId;
                String libraryData = firebaseLibrary.data;
                if (libraryData.contains(".")) {
                    databaseUrl = "https://" + libraryData;
                    projectId = libraryData.trim().replaceAll(FIREBASE_DATABASE_STORAGE_LOCATION_MATCHER, "");
                } else {
                    databaseUrl = "https://" + libraryData + ".firebaseio.com";
                    projectId = libraryData;
                }
                mx.addString("firebase_database_url", databaseUrl, false);
                mx.addString("project_id", projectId, false);
                mx.addString("google_app_id", firebaseLibrary.reserved1, false);
                if (firebaseLibrary.reserved2 != null && !firebaseLibrary.reserved2.isEmpty()) {
                    mx.addString("google_api_key", firebaseLibrary.reserved2, false);
                }
                if (firebaseLibrary.reserved3 != null && !firebaseLibrary.reserved3.isEmpty()) {
                    mx.addString("google_storage_bucket", firebaseLibrary.reserved3, false);
                }
            }
            if (N.isMapUsed) {
                mx.addString("google_maps_key", projectLibraryManager.e().data, false);
            }
            String filePath = "values/secrets.xml";
            fileUtil.b(resDirectoryPath + File.separator + filePath,
                    CommandBlock.applyCommands(filePath, mx.toCode()));
        }
        generateGradleFiles();
    }

    public ArrayList<SrcCodeBean> a(hC projectFileManager, eC projectDataManager, BuiltInLibraryManager builtInLibraryManager) {
        generateDebugFiles(SketchApplication.getContext());
        CommandBlock.x();

        String javaDir = FileUtil.getExternalStorageDir() + "/.sketchware/data/" + sc_id + "/files/java/";
        String layoutDir = FileUtil.getExternalStorageDir() + "/.sketchware/data/" + sc_id + "/files/resource/layout/";
        
        String customJavaDir = FileUtil.getExternalStorageDir() + "/.sketchware/data/" + sc_id + "/custom_java/";
        String customManifestPath = FileUtil.getExternalStorageDir() + "/.sketchware/data/" + sc_id + "/custom_manifest.xml";

        boolean isCustomJavaEnabled = projectSettings.getValue(ProjectSettings.SETTING_ENABLE_CUSTOM_JAVA, "false").equals("true");
        boolean isCustomManifestEnabled = projectSettings.getValue(ProjectSettings.SETTING_ENABLE_CUSTOM_MANIFEST, "false").equals("true");

        List<File> javaFiles = new ArrayList<>();
        File[] fArr = new File(javaDir).listFiles();
        if (fArr != null) javaFiles = Arrays.asList(fArr);

        List<File> layoutFiles = new ArrayList<>();
        File[] lArr = new File(layoutDir).listFiles();
        if (lArr != null) layoutFiles = Arrays.asList(lArr);

        ArrayList<SrcCodeBean> srcCodeBeans = new ArrayList<>();
        
        for (ProjectFileBean activity : projectFileManager.b()) {
            File customJavaFile = new File(customJavaDir, activity.getJavaName());
            
            if (isCustomJavaEnabled && customJavaFile.exists()) {
                srcCodeBeans.add(new SrcCodeBean(activity.getJavaName(), FileUtil.readFile(customJavaFile.getAbsolutePath())));
            } else if (!javaFiles.contains(new File(javaDir + activity.getJavaName()))) {
                srcCodeBeans.add(new SrcCodeBean(activity.getJavaName(),
                        new Jx(N, activity, projectDataManager).generateCode(isAndroidStudioExport, sc_id)));
            } else {
                srcCodeBeans.add(new SrcCodeBean(activity.getJavaName(), FileUtil.readFile(javaDir + activity.getJavaName())));
            }
        }

        var path = wq.b(sc_id) + "/command";
        var newXMLCommand = Boolean.parseBoolean(projectSettings.getValue(ProjectSettings.SETTING_NEW_XML_COMMAND, ProjectSettings.SETTING_GENERIC_VALUE_FALSE));
        if (newXMLCommand && FileUtil.isExistFile(path)) {
            FileUtil.copyFile(path, FileUtil.getExternalStorageDir().concat("/.sketchware/temp/commands"));
        }

        var viewBindingBuilder = new ViewBindingBuilder(List.of(), new File("."), packageName);

        ArrayList<ProjectFileBean> regularLayouts = projectFileManager.b();
        for (ProjectFileBean layout : regularLayouts) {
            String xmlName = layout.getXmlName();
            Ox ox = new Ox(N, layout);
            ox.a(eC.a(projectDataManager.d(xmlName)), projectDataManager.h(xmlName));
            var ogFile = new File(layoutDir + xmlName);
            if (!layoutFiles.contains(ogFile)) {
                srcCodeBeans.add(new SrcCodeBean(xmlName, CommandBlock.applyCommands(xmlName, ox.b())));

                if (isViewBindingEnable()) {
                    var privFile = new File(context.getCacheDir(), xmlName);
                    FileUtil.writeFile(privFile.getAbsolutePath(), CommandBlock.applyCommands(xmlName, ox.b()));
                    var code = viewBindingBuilder.generateBindingForLayout(privFile);
                    srcCodeBeans.add(new SrcCodeBean(
                            ViewBindingBuilder.generateFileNameForLayout(xmlName.replace(".xml", "")) + ".java",
                            CommandBlock.applyCommands(xmlName, code)
                    ));
                }
            }
        }

        ArrayList<ProjectFileBean> customViewFiles = projectFileManager.c();
        for (ProjectFileBean customViewFile : customViewFiles) {
            String xmlName = customViewFile.getXmlName();
            Ox ox = new Ox(N, customViewFile);
            ox.a(eC.a(projectDataManager.d(xmlName)));
            var ogFile = new File(layoutDir + xmlName);
            if (!layoutFiles.contains(ogFile)) {
                srcCodeBeans.add(new SrcCodeBean(xmlName, CommandBlock.applyCommands(xmlName, ox.b())));

                if (isViewBindingEnable()) {
                    var privFile = new File(context.getCacheDir(), xmlName);
                    FileUtil.writeFile(privFile.getAbsolutePath(), CommandBlock.applyCommands(xmlName, ox.b()));
                    var code = viewBindingBuilder.generateBindingForLayout(privFile);
                    srcCodeBeans.add(new SrcCodeBean(
                            ViewBindingBuilder.generateFileNameForLayout(xmlName.replace(".xml", "")) + ".java",
                            CommandBlock.applyCommands(xmlName, code)
                    ));
                }
            }
        }

        Ix ix = new Ix(N, projectFileManager.b(), builtInLibraryManager);
        ix.setYq(this);

        if (!javaFiles.contains(new File(javaDir + "SketchwareUtil.java"))) {
            srcCodeBeans.add(new SrcCodeBean("SketchwareUtil.java",
                    Lx.i(packageName, material3LibraryManager.isMaterial3Enabled())));
        }

        if (!javaFiles.contains(new File(javaDir + "FileUtil.java"))) {
            srcCodeBeans.add(new SrcCodeBean("FileUtil.java", Lx.e(packageName)));
        }

        if (!javaFiles.contains(new File(javaDir + "RequestNetwork.java")) && N.isHttp3Used) {
            srcCodeBeans.add(new SrcCodeBean("RequestNetwork.java", Lx.j(Lx.h(packageName), false)));
        }

        if (!FileUtil.isExistFile(javaDir + "RequestNetworkController.java") && N.isHttp3Used) {
            srcCodeBeans.add(new SrcCodeBean("RequestNetworkController.java", Lx.j(Lx.g(packageName), false)));
        }

        if (!javaFiles.contains(new File(javaDir + "BluetoothConnect.java")) && N.hasPermission(jq.PERMISSION_BLUETOOTH)) {
            srcCodeBeans.add(new SrcCodeBean("BluetoothConnect.java", Lx.j(Lx.b(packageName), false)));
        }

        if (!javaFiles.contains(new File(javaDir + "BluetoothController.java")) && N.hasPermission(jq.PERMISSION_BLUETOOTH)) {
            srcCodeBeans.add(new SrcCodeBean("BluetoothController.java", Lx.j(Lx.c(packageName), false)));
        }

        if (N.isMapUsed && !javaFiles.contains(new File(javaDir + "GoogleMapController.java"))) {
            srcCodeBeans.add(new SrcCodeBean("GoogleMapController.java", Lx.j(Lx.f(packageName), false)));
        }

        if (isCustomManifestEnabled && FileUtil.isExistFile(customManifestPath)) {
            srcCodeBeans.add(new SrcCodeBean("AndroidManifest.xml", FileUtil.readFile(customManifestPath)));
        } else {
            srcCodeBeans.add(new SrcCodeBean("AndroidManifest.xml", CommandBlock.applyCommands("AndroidManifest.xml", ix.a())));
        }
        
        srcCodeBeans.add(new SrcCodeBean("styles.xml", getXMLStyle()));
        srcCodeBeans.add(new SrcCodeBean("colors.xml", getXMLColor()));
        srcCodeBeans.add(new SrcCodeBean("strings.xml", getXMLString()));
        CommandBlock.x();
        return srcCodeBeans;
    }

    private boolean isViewBindingEnable() {
        return generateDataBindingClasses && projectSettings.getValue(ProjectSettings.SETTING_ENABLE_VIEWBINDING, ProjectSettings.SETTING_GENERIC_VALUE_FALSE).equals(ProjectSettings.SETTING_GENERIC_VALUE_TRUE);
    }

    public String getFileSrc(String filename, hC projectFileManager, eC projectDataManager, iC projectLibraryManager) {
        a(projectLibraryManager, projectFileManager, projectDataManager);
        CommandBlock.x();
        boolean isJavaFile = filename.endsWith(".java");
        boolean isXmlFile = filename.endsWith(".xml");
        boolean isManifestFile = filename.equals("AndroidManifest.xml");
        ArrayList<ProjectFileBean> files = new ArrayList<>(projectFileManager.b());
        files.addAll(new ArrayList<>(projectFileManager.c()));
        
        boolean isCustomJavaEnabled = projectSettings.getValue(ProjectSettings.SETTING_ENABLE_CUSTOM_JAVA, "false").equals("true");
        boolean isCustomManifestEnabled = projectSettings.getValue(ProjectSettings.SETTING_ENABLE_CUSTOM_MANIFEST, "false").equals("true");

        if (isXmlFile) {
            var path = wq.b(sc_id) + "/command";
            var newXMLCommand = Boolean.parseBoolean(projectSettings.getValue(ProjectSettings.SETTING_NEW_XML_COMMAND, ProjectSettings.SETTING_GENERIC_VALUE_FALSE));
            if (newXMLCommand && FileUtil.isExistFile(path)) {
                FileUtil.copyFile(path, FileUtil.getExternalStorageDir().concat("/.sketchware/temp/commands"));
            } else {
                for (ProjectFileBean file : files) {
                    CommandBlock.CBForXml(new Jx(N, file, projectDataManager).generateCode(isAndroidStudioExport, sc_id));
                }
            }
        }

        switch (filename) {
            case "strings.xml" -> { return getXMLString(); }
            case "colors.xml" -> { return getXMLColor(); }
            case "styles.xml" -> { return getXMLStyle(); }
        }


        if (isManifestFile) {
            String customManifestPath = FileUtil.getExternalStorageDir() + "/.sketchware/data/" + sc_id + "/custom_manifest.xml";
            if (isCustomManifestEnabled && FileUtil.isExistFile(customManifestPath)) {
                return FileUtil.readFile(customManifestPath);
            }
            
            ProjectBuilder builder = new ProjectBuilder(SketchApplication.getContext(), this);
            builder.buildBuiltInLibraryInformation();
            Ix ix = new Ix(N, projectFileManager.b(), builder.getBuiltInLibraryManager());
            ix.setYq(this);
            return CommandBlock.applyCommands("AndroidManifest.xml", ix.a());
        }

        for (ProjectFileBean file : files) {
            if (filename.equals(isJavaFile ? file.getJavaName() : file.getXmlName())) {
                if (isJavaFile) {
                    String customJavaPath = FileUtil.getExternalStorageDir() + "/.sketchware/data/" + sc_id + "/custom_java/" + filename;
                    if (isCustomJavaEnabled && FileUtil.isExistFile(customJavaPath)) {
                        return FileUtil.readFile(customJavaPath);
                    }
                    return new Jx(N, file, projectDataManager).generateCode(isAndroidStudioExport, sc_id);
                } else if (isXmlFile) {
                    Ox xmlGenerator = new Ox(N, file);
                    xmlGenerator.a(eC.a(projectDataManager.d(filename)), projectDataManager.h(filename));
                    return CommandBlock.applyCommands(filename, xmlGenerator.b());
                }
            }
        }
        return "";
    }

    public String getXMLString() {
        String filePath = wq.b(sc_id) + "/files/resource/values/strings.xml";
        if (FileUtil.isExistFile(filePath) && exportingType == ExportType.SOURCE_CODE_VIEWING) {
            return FileUtil.readFile(filePath);
        }
        XmlBuilderHelper stringsFileBuilder = new XmlBuilderHelper();
        stringsFileBuilder.addNonTranslatableString("app_name", applicationName);
        return CommandBlock.applyCommands("strings.xml", stringsFileBuilder.toCode());
    }

    public String getXMLColor() {
        String filePath = wq.b(sc_id) + "/files/resource/values/colors.xml";
        if (FileUtil.isExistFile(filePath) && exportingType == ExportType.SOURCE_CODE_VIEWING) {
            return FileUtil.readFile(filePath);
        }
        XmlBuilderHelper colorsFileBuilder = new XmlBuilderHelper();
        colorsFileBuilder.addColor("colorPrimary", String.format("#%06X", colorPrimary & 0xffffff));
        colorsFileBuilder.addColor("colorPrimaryDark", String.format("#%06X", colorPrimaryDark & 0xffffff));
        colorsFileBuilder.addColor("colorAccent", String.format("#%06X", colorAccent & 0xffffff));
        colorsFileBuilder.addColor("colorControlHighlight", String.format("#%06X", colorControlHighlight & 0xffffff));
        colorsFileBuilder.addColor("colorControlNormal", String.format("#%06X", colorControlNormal & 0xffffff));
        return CommandBlock.applyCommands("colors.xml", colorsFileBuilder.toCode());
    }

    public String getXMLStyle() {
        String filePath = wq.b(sc_id) + "/files/resource/values/styles.xml";
        if (FileUtil.isExistFile(filePath) && exportingType == ExportType.SOURCE_CODE_VIEWING) {
            return FileUtil.readFile(filePath);
        }
        if (material3LibraryManager.isMaterial3Enabled()) {
            XmlBuilderHelper stylesFileBuilder = new XmlBuilderHelper();
            stylesFileBuilder.addStyle("AppTheme", String.format("Theme.Material3.%s.NoActionBar", material3LibraryManager.getTheme()));
            stylesFileBuilder.addItemToStyle("AppTheme", "android:statusBarColor", "@android:color/transparent");
            stylesFileBuilder.addItemToStyle("AppTheme", "android:navigationBarColor", "@android:color/transparent");
            stylesFileBuilder.addItemToStyle("AppTheme", "android:windowLightStatusBar", "?attr/isLightTheme");
            stylesFileBuilder.addStyle("AppTheme.FullScreen", "AppTheme");
            stylesFileBuilder.addItemToStyle("AppTheme.FullScreen", "android:windowFullscreen", "true");
            stylesFileBuilder.addItemToStyle("AppTheme.FullScreen", "android:windowContentOverlay", "@null");
            stylesFileBuilder.addStyle("AppTheme.AppBarOverlay", "ThemeOverlay.Material3");
            stylesFileBuilder.addStyle("AppTheme.PopupOverlay", "ThemeOverlay.Material3");
            stylesFileBuilder.addStyle("AppTheme.DebugActivity", "AppTheme");
            stylesFileBuilder.addItemToStyle("AppTheme.DebugActivity", "windowActionBar", "true");
            stylesFileBuilder.addItemToStyle("AppTheme.DebugActivity", "windowNoTitle", "false");
            return CommandBlock.applyCommands("styles.xml", stylesFileBuilder.toCode());
        } else if (N.g) {
            boolean useNewMaterialComponentsTheme = projectSettings.getValue(ProjectSettings.SETTING_ENABLE_BRIDGELESS_THEMES,
                    BuildSettings.SETTING_GENERIC_VALUE_FALSE).equals(BuildSettings.SETTING_GENERIC_VALUE_TRUE);
            XmlBuilderHelper stylesFileBuilder = new XmlBuilderHelper();
            stylesFileBuilder.addStyle("AppTheme", "Theme.MaterialComponents.Light.NoActionBar" + (useNewMaterialComponentsTheme ? "" : ".Bridge"));
            stylesFileBuilder.addItemToStyle("AppTheme", "colorOnPrimary", "@android:color/white");
            stylesFileBuilder.addItemToStyle("AppTheme", "colorPrimary", "@color/colorPrimary");
            stylesFileBuilder.addItemToStyle("AppTheme", "colorPrimaryDark", "@color/colorPrimaryDark");
            stylesFileBuilder.addItemToStyle("AppTheme", "colorAccent", "@color/colorAccent");
            stylesFileBuilder.addItemToStyle("AppTheme", "colorControlHighlight", "@color/colorControlHighlight");
            stylesFileBuilder.addItemToStyle("AppTheme", "colorControlNormal", "@color/colorControlNormal");

            stylesFileBuilder.addStyle("AppTheme.FullScreen", "AppTheme");
            stylesFileBuilder.addItemToStyle("AppTheme.FullScreen", "android:windowFullscreen", "true");
            stylesFileBuilder.addItemToStyle("AppTheme.FullScreen", "android:windowContentOverlay", "@null");

            stylesFileBuilder.addStyle("AppTheme.AppBarOverlay", "ThemeOverlay.MaterialComponents.Dark.ActionBar");
            stylesFileBuilder.addStyle("AppTheme.PopupOverlay", "ThemeOverlay.MaterialComponents.Light");

            stylesFileBuilder.addStyle("AppTheme.DebugActivity", "AppTheme");
            stylesFileBuilder.addItemToStyle("AppTheme.DebugActivity", "actionBarStyle", "@style/ThemeOverlay.MaterialComponents.ActionBar.Primary");
            stylesFileBuilder.addItemToStyle("AppTheme.DebugActivity", "actionBarTheme", "@style/Widget.MaterialComponents.ActionBar.Primary");
            stylesFileBuilder.addItemToStyle("AppTheme.DebugActivity", "windowActionBar", "true");
            stylesFileBuilder.addItemToStyle("AppTheme.DebugActivity", "windowNoTitle", "false");
            return CommandBlock.applyCommands("styles.xml", stylesFileBuilder.toCode());
        } else {
            XmlBuilderHelper stylesFileBuilder = new XmlBuilderHelper();
            stylesFileBuilder.addStyle("AppTheme", "@android:style/Theme.Material.Light.DarkActionBar");
            stylesFileBuilder.addItemToStyle("AppTheme", "android:colorPrimary", "@color/colorPrimary");
            stylesFileBuilder.addItemToStyle("AppTheme", "android:colorPrimaryDark", "@color/colorPrimaryDark");
            stylesFileBuilder.addItemToStyle("AppTheme", "android:colorAccent", "@color/colorAccent");
            stylesFileBuilder.addItemToStyle("AppTheme", "android:colorControlHighlight", "@color/colorControlHighlight");
            stylesFileBuilder.addItemToStyle("AppTheme", "android:colorControlNormal", "@color/colorControlNormal");
            stylesFileBuilder.addStyle("FullScreen", "@android:style/Theme.Material.Light.NoActionBar.Fullscreen");
            stylesFileBuilder.addItemToStyle("FullScreen", "android:colorPrimary", "@color/colorPrimary");
            stylesFileBuilder.addItemToStyle("FullScreen", "android:colorPrimaryDark", "@color/colorPrimaryDark");
            stylesFileBuilder.addItemToStyle("FullScreen", "android:colorAccent", "@color/colorAccent");
            stylesFileBuilder.addItemToStyle("FullScreen", "android:colorControlHighlight", "@color/colorControlHighlight");
            stylesFileBuilder.addItemToStyle("FullScreen", "android:colorControlNormal", "@color/colorControlNormal");
            stylesFileBuilder.addStyle("NoActionBar", "@android:style/Theme.Material.Light.NoActionBar");
            stylesFileBuilder.addItemToStyle("NoActionBar", "android:colorPrimary", "@color/colorPrimary");
            stylesFileBuilder.addItemToStyle("NoActionBar", "android:colorPrimaryDark", "@color/colorPrimaryDark");
            stylesFileBuilder.addItemToStyle("NoActionBar", "android:colorAccent", "@color/colorAccent");
            stylesFileBuilder.addItemToStyle("NoActionBar", "android:colorControlHighlight", "@color/colorControlHighlight");
            stylesFileBuilder.addItemToStyle("NoActionBar", "android:colorControlNormal", "@color/colorControlNormal");
            stylesFileBuilder.addStyle("NoStatusBar", "AppTheme");
            stylesFileBuilder.addItemToStyle("NoStatusBar", "android:windowFullscreen", "true");
            stylesFileBuilder.addStyle("AppTheme.DebugActivity", "AppTheme");
            return CommandBlock.applyCommands("styles.xml", stylesFileBuilder.toCode());
        }
    }

    public enum ExportType {
        AAB, SIGN_APP, DEBUG_APP, ANDROID_STUDIO, SOURCE_CODE_VIEWING
    }
}
